### ISSUE TITLE
ModuleNotFoundError: No module named '_cffi_backend'

### ISSUE THREAD

**Issue by littleWang1** [bear-zd/ChaoXingReserveSeat#16]
我已经安装ciff这个包了 但是报这个错误ModuleNotFoundError: No module named '_cffi_backend'

**Comment by bear-zd** [comment]
可以提供详细的报错吗，因为这个报错应该是在导入其他包的时候引起的，目前提供的信息不足以让我知道是哪个包导入有问题。

**Comment by littleWang1** [comment]
pydev debugger: process 23672 is connecting

Connected to pydev debugger (build 201.7223.92)
start time 12:33:27
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\Python\Python39\lib\site-packages\cryptography\hazmat\backends\openssl\__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "D:\Python\Python39\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "D:\Python\Python39\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 64, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "D:\Python\Python39\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "D:\Python\Python39\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
  File "D:\Python\Python39\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "D:\Python\Python39\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named '_cffi_backend'
这是控制台详细的信息哈

**Comment by bear-zd** [comment]
看上去像是一些依赖冲突混进去了奇怪的东西，看了一下我这边的cryptography库，可能有两个原因：
1、有个shiboken2库在其中反复出现可能是引入冲突了，试试删除该库
2、python版本过低导致的
