### ISSUE TITLE
行为验证码问题

### ISSUE THREAD

**Issue by longllovers** [bear-zd/ChaoXingReserveSeat#18]

**Comment by longllovers** [comment]
进入学校的图书馆预约系统，当提交坐位选择时候，需要行为验证码，点击图形的验证码方式，不知道该项目还能不能使用，或者，还有什么办法在破解该验证码，希望作者帮帮忙，看看能不能解决

**Comment by longllovers** [comment]
明确下验证码类型，是点选式的验证码

**Comment by NeptuneKai** [comment]
链接发一下看看

**Comment by NeptuneKai** [comment]
> 明确下验证码类型，是点选式的验证码

发个链接看一下

**Comment by longllovers** [comment]
![82ec9c4e85a3506d6f701146090f7d5](https://github.com/bear-zd/ChaoXingReserveSeat/assets/141143732/a228eef9-2674-4fc9-af99-f042d19bccd7)
这样的

**Comment by mfornothing** [comment]
这个怎么解决呢
2024-09-24 17:21:15,706 - INFO - Captcha Image URL-small https://captcha-b.chaoxing.com/slide/small/DE52333D983C5060D8774CF1FB4DF17D.jpg, URL-big https://captcha-b.chaoxing.com/slide/big/DE52333D983C5060D8774CF1FB4DF17D.jpg
Traceback (most recent call last):
File "C:\Users\m\Desktop\ChaoXingReserveSeat-rebuild\main.py", line 117, in
func_dict[args.method](usersdata, args.action)
File "C:\Users\m\Desktop\ChaoXingReserveSeat-rebuild\main.py", line 62, in main
success_list = login_and_reserve(users, usernames, passwords, action, success_list)
File "C:\Users\m\Desktop\ChaoXingReserveSeat-rebuild\main.py", line 44, in login_and_reserve
suc = s.submit(times, roomid, seatid, action)
File "C:\Users\m\Desktop\ChaoXingReserveSeat-rebuild\utils\reserve.py", line 205, in submit
captcha = self.resolve_captcha() if self.enable_slider else ""
File "C:\Users\m\Desktop\ChaoXingReserveSeat-rebuild\utils\reserve.py", line 106, in resolve_captcha
x = self.x_distance(bg, tp)
File "C:\Users\m\Desktop\ChaoXingReserveSeat-rebuild\utils\reserve.py", line 189, in x_distance
tp_img = cut_slide(tp)
File "C:\Users\m\Desktop\ChaoXingReserveSeat-rebuild\utils\reserve.py", line 166, in cut_slide
slider_part = slider_image[:, :, :3]
TypeError: 'NoneType' object is not subscriptable

**Comment by bear-zd** [comment]
这个问题和这个issue无关，建议提交新的issue，继续回复会影响到其他用户。

**Comment by mfornothing** [comment]
> 这个问题和这个issue无关，建议提交新的issue，继续回复会影响到其他用户。

这个是行为验证码问题啊

**Comment by bear-zd** [comment]
日志不全无法知道具体的原因。
可能是你们学校预约不需要滑块验证（有人遇到过类似的问题），把如果是rebuild分支的话就把main.py中的ENABLE_SLIDER改为False，如果是ext分支的话就把reserve = CAPTCHA_METHOD["custom"] 的custom改成 default.
