### ISSUE TITLE
脚本文件不能结束

### ISSUE THREAD

**Issue by Akonsting** [bear-zd/ChaoXingReserveSeat#26]
我在ubuntu22.04上运行时遇到以下反馈：

Traceback (most recent call last):
  File "/root/qiangzuo1/main.py", line 117, in <module>
    func_dict[args.method](usersdata, args.action)
  File "/root/qiangzuo1/main.py", line 62, in main
    success_list = login_and_reserve(users, usernames, passwords, action, success_list)
  File "/root/qiangzuo1/main.py", line 44, in login_and_reserve
    suc = s.submit(times, roomid, seatid, action)
  File "/root/qiangzuo1/utils/reserve.py", line 205, in submit
    captcha = self.resolve_captcha() if self.enable_slider else "" 
  File "/root/qiangzuo1/utils/reserve.py", line 103, in resolve_captcha
    captcha_token, bg, tp = self.get_slide_captcha_data()
  File "/root/qiangzuo1/utils/reserve.py", line 149, in get_slide_captcha_data
    response = self.requests.get(url=url, params=params, headers=self.headers)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 557, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 544, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 657, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 700, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 446, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 441, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1303, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1159, in read
    return self._sslobj.read(len, buffer)
KeyboardInterrupt
导致程序不能终止，这问题该怎么解决？

**Comment by bear-zd** [comment]
请提供一下运行方式以及参数
我能看出来的只有你ctrl+c中断程序

**Comment by Akonsting** [comment]
> 请提供一下运行方式以及参数
> 我能看出来的只有你ctrl+c中断程序

在ubuntu22.04云服务器上通过/usr/bin/python3 /root/ChaoXingReserveSeat/main.py >> /root/ReserveSeat.log 2>&1命令运行，sleeptime设为0.1，最大尝试次数设为20。

而且下午在另一次测试中，通过crontab定时运行时，sleeptime为0.1，最大尝试次数为20，却一直在运行，直到一小时后我手动终止，日志文件里显示一共尝试了接近三百次。

**Comment by bear-zd** [comment]
因为他是到预约开始时的一分钟后才停止，你从下午测试那自然会一直运行到第二天早上7:01（默认设置的），你可以调整这个参数。所以我在readme的crontab中写的是7点每天开始运行（0 7 * * *），到7:01停止，运行没有太大问题
