### ISSUE TITLE
1

### ISSUE THREAD

**Issue by mfornothing** [bear-zd/ChaoXingReserveSeat#39]

**Comment by mfornothing** [comment]
> 2024-09-24 17:21:15,706 - INFO - Captcha Image URL-small https://captcha-b.chaoxing.com/slide/small/DE52333D983C5060D8774CF1FB4DF17D.jpg, URL-big https://captcha-b.chaoxing.com/slide/big/DE52333D983C5060D8774CF1FB4DF17D.jpg
> Traceback (most recent call last):
> File "C:\Users\m\Desktop\ChaoXingReserveSeat-rebuild\main.py", line 117, in
> func_dict[args.method](usersdata, args.action)
> File "C:\Users\m\Desktop\ChaoXingReserveSeat-rebuild\main.py", line 62, in main
> success_list = login_and_reserve(users, usernames, passwords, action, success_list)
> File "C:\Users\m\Desktop\ChaoXingReserveSeat-rebuild\main.py", line 44, in login_and_reserve
> suc = s.submit(times, roomid, seatid, action)
> File "C:\Users\m\Desktop\ChaoXingReserveSeat-rebuild\utils\reserve.py", line 205, in submit
> captcha = self.resolve_captcha() if self.enable_slider else ""
> File "C:\Users\m\Desktop\ChaoXingReserveSeat-rebuild\utils\reserve.py", line 106, in resolve_captcha
> x = self.x_distance(bg, tp)
> File "C:\Users\m\Desktop\ChaoXingReserveSeat-rebuild\utils\reserve.py", line 189, in x_distance
> tp_img = cut_slide(tp)
> File "C:\Users\m\Desktop\ChaoXingReserveSeat-rebuild\utils\reserve.py", line 166, in cut_slide
> slider_part = slider_image[:, :, :3]
> TypeError: 'NoneType' object is not subscriptable
