### ISSUE TITLE
貌似是滑动验证出问题

### ISSUE THREAD

**Issue by LISAooo1234** [bear-zd/ChaoXingReserveSeat#41]
2024-09-25 23:36:22,055 - INFO - User CBwQdCrSBSV8Toy+8lkboA== login successfully
2024-09-25 23:36:22,569 - INFO - Get token: 8da8688b97454d509ca5f6c3bedc64c5
2024-09-25 23:36:22,569 - INFO - Start to resolve captcha token
2024-09-25 23:36:22,645 - INFO - Successfully get prepared captcha_token 6966791931C4C3CB8156C306DB63F0A1
2024-09-25 23:36:22,645 - INFO - Captcha Image URL-small https://captcha-b.chaoxing.com/slide/small/C19CDC1ED2E72EA3E21B169443CEBA76.jpg, URL-big https://captcha-b.chaoxing.com/slide/big/C19CDC1ED2E72EA3E21B169443CEBA76.jpg
Traceback (most recent call last):
  File "d:\VSC-Python\ChaoXingReserveSeat-rebuild\main.py", line 117, in <module>
    func_dict[args.method](usersdata, args.action)
  File "d:\VSC-Python\ChaoXingReserveSeat-rebuild\main.py", line 62, in main
    success_list = login_and_reserve(users, usernames, passwords, action, success_list)
  File "d:\VSC-Python\ChaoXingReserveSeat-rebuild\main.py", line 44, in login_and_reserve
    suc = s.submit(times, roomid, seatid, action)
  File "d:\VSC-Python\ChaoXingReserveSeat-rebuild\utils\reserve.py", line 208, in submit
    captcha = self.resolve_captcha() if self.enable_slider else ""
  File "d:\VSC-Python\ChaoXingReserveSeat-rebuild\utils\reserve.py", line 106, in resolve_captcha
    x = self.x_distance(bg, tp)
  File "d:\VSC-Python\ChaoXingReserveSeat-rebuild\utils\reserve.py", line 192, in x_distance
    tp_img = cut_slide(tp)
  File "d:\VSC-Python\ChaoXingReserveSeat-rebuild\utils\reserve.py", line 169, in cut_slide
    slider_part = slider_image[:, :, :3]
TypeError: 'NoneType' object is not subscriptable

**Comment by bear-zd** [comment]
可能是你们学校预约不需要滑块验证（有人遇到过类似的问题），如果是rebuild分支的话就把main.py中的ENABLE_SLIDER改为False，如果是ext分支的话就把reserve = CAPTCHA_METHOD["custom"] 的custom改成 default 就好了.

**Comment by tomgaveen** [comment]
哥们儿 只要把c_captcha_headers里面的host的
captha-c改为captha-b就行了！！！！！！ 我找了好久

**Comment by bear-zd** [comment]
哈哈哈解决了就好
