### ISSUE TITLE
action off

### ISSUE THREAD

**Issue by doing-well** [bear-zd/ChaoXingReserveSeat#43]
![ff4590b06dd22bbe548a5232315a7f50](https://github.com/user-attachments/assets/7b7bb7ee-7d01-46bd-834f-be619d98ebe2)
2024-09-27 22:30:06,253 - INFO - start time 22:30:06, action off是我哪里出了问题

**Comment by bear-zd** [comment]
没到预约启动前的1min时间 如果想要测试使用 python main.py --debug

**Comment by doing-well** [comment]
我在其他Issues看到您说可能是因为没有滑块验证导致，但是我更改之后ENABLE_SLIDER就变成预约失败了：
 INFO - {'msg': '预约失败，请退出后重试！', 'success': False}
另外我们学校确实是有滑块验证的，还是说是其他原因
024-09-28 19:56:18,316 - INFO - User X24tuY4ICXajt7pvYt70lQ== login successfully
2024-09-28 19:56:19,237 - INFO - Get token: 
2024-09-28 19:56:19,237 - INFO - Start to resolve captcha token
2024-09-28 19:56:19,590 - INFO - Successfully get prepared captcha_token 2A4E7609E29A69DB50CD361FC9E3D205
2024-09-28 19:56:19,590 - INFO - Captcha Image URL-small https://captcha-b.chaoxing.com/slide/small/DFD742B9027C08E31F9E30959EA5611A.jpg, URL-big https://captcha-b.chaoxing.com/slide/big/DFD742B9027C08E31F9E30959EA5611A.jpg
Traceback (most recent call last):
  File "c:\Users\d5120\Desktop\ChaoXingReserveSeat-rebuild\main.py", line 117, in <module>
    func_dict[args.method](usersdata, args.action)
  File "c:\Users\d5120\Desktop\ChaoXingReserveSeat-rebuild\main.py", line 62, in main
    success_list = login_and_reserve(users, usernames, passwords, action, success_list)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\d5120\Desktop\ChaoXingReserveSeat-rebuild\main.py", line 44, in login_and_reserve
    suc = s.submit(times, roomid, seatid, action)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\d5120\Desktop\ChaoXingReserveSeat-rebuild\utils\reserve.py", line 205, in submit
    captcha = self.resolve_captcha() if self.enable_slider else ""
              ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\d5120\Desktop\ChaoXingReserveSeat-rebuild\utils\reserve.py", line 106, in resolve_captcha
    x = self.x_distance(bg, tp)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\d5120\Desktop\ChaoXingReserveSeat-rebuild\utils\reserve.py", line 189, in x_distance
    tp_img = cut_slide(tp)
             ^^^^^^^^^^^^^
  File "c:\Users\d5120\Desktop\ChaoXingReserveSeat-rebuild\utils\reserve.py", line 166, in cut_slide
    slider_part = slider_image[:, :, :3]
                  ~~~~~~~~~~~~^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by bear-zd** [comment]
贵校手动预约需要滑块验证吗，如果不需要的话开启会报这个错误的

**Comment by bear-zd** [comment]
#46 如果没有解决的话尝试一下该操作

**Comment by doing-well** [comment]
成功了，他说的是对的
