### ISSUE TITLE
麻烦大佬给看看我这啥问题

### ISSUE THREAD

**Issue by Angelysss** [bear-zd/ChaoXingReserveSeat#55]
mikey@Thinkbook-X270 rs % python3 main.py -m debug
Traceback (most recent call last):
  File "/Users/mikey/rs/main.py", line 10, in <module>
    from utils import reserve, get_user_credentials
  File "/Users/mikey/rs/utils/__init__.py", line 3, in <module>
    from .reserve import reserve
  File "/Users/mikey/rs/utils/reserve.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by bear-zd** [comment]
没有requests库，`pip install requests`
