### ISSUE TITLE
有时可预约到，有时预约不到,缺失对应日志不知道如何debug

### ISSUE THREAD

**Issue by xiyue1753** [bear-zd/ChaoXingReserveSeat#62]
Run python main.py -m debug --action
2024-12-13 22:5[9](https://github.com/xiyue1753/ChaoXingReserveSeat/actions/runs/12324295844/job/34401579805#step:5:10):58,904 - INFO - Global settings: 
SLEEPTIME: 0.2
ENDTIME: 07:01:00
ENABLE_SLIDER: False
RESERVE_NEXT_DAY: False
2024-12-13 22:59:58,904 - INFO -  Debug Mode start! , action on
2024-12-13 22:59:58,904 - INFO - ----------- *** -- ['08:30', '20:30'] -- ['060'] try -----------
2024-12-13 23:00:00,752 - INFO - User W0bd/yjltQYUEWm/7nX07Q== login successfully
2024-12-13 23:00:02,978 - INFO - Get token: 7242be73dbbe4806995e6c5cd15db4fd
2024-12-13 23:00:02,978 - INFO - Captcha token 
2024-12-13 23:00:02,978 - INFO - submit parameter {'roomId': '6675', 'startTime': '08:30', 'endTime': '20:30', 'day': '2024-12-14', 'seatNum': '060', 'captcha': '', 'token': '7242be73dbbe4806995e6c5cd15db4fd'} 
Traceback (most recent call last):
  File "/home/runner/work/ChaoXingReserveSeat/ChaoXingReserveSeat/main.py", line [11](https://github.com/xiyue1753/ChaoXingReserveSeat/actions/runs/12324295844/job/34401579805#step:5:12)7, in <module>
    func_dict[args.method](usersdata, args.action)
  File "/home/runner/work/ChaoXingReserveSeat/ChaoXingReserveSeat/main.py", line 92, in debug
    suc = s.submit(times, roomid, seatid, action)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/ChaoXingReserveSeat/ChaoXingReserveSeat/utils/reserve.py", line 207, in submit
    suc = self.get_submit(self.submit_url, times=times,token=token, roomid=roomid, seatid=seat, captcha=captcha, action=action)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/ChaoXingReserveSeat/ChaoXingReserveSeat/utils/reserve.py", line 233, in get_submit
    times[0] + "~" + times[1] + ':  ' + str(json.loads(html)))
                                            ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Error: Process completed with exit code 1.

**Comment by bear-zd** [comment]
看样子是在发送请求获取json的时候没有获得到内容，这个可能是网络波动导致的？

**Comment by xiyue1753** [comment]
我也猜想有这种可能,感谢解惑
